name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    uses: EvergineTeam/evergine-standards/workflows/binding/_ci-reusable.yml@main
    with:
      project-name: "Binding Project"
      main-branch: "main"
      version-param: "revision"
      dotnet-version: "8.x"
      nuget-version: "6.x"
      bindings-script: "./Generate-Bindings-DotNet.ps1"
      nugets-script: "./Generate-NuGets-DotNet.ps1"
      generator-project: "Generator\\Generator\\Generator.csproj"
      generator-name: "BindingName"
      target-framework: "net8.0"
      runtime-identifier: ""
      projects: "Binding\\Evergine.Bindings.Example\\Evergine.Bindings.Example.csproj"
      output-folder: "nupkgs"
      build-verbosity: "normal"
      build-configuration: "Release"
      include-symbols: false
      symbols-format: "snupkg"
      enable-email-notifications: true
    secrets:
      SENDGRID_TOKEN: ${{ secrets.WAVE_SENDGRID_TOKEN }}
      EMAIL_REPORT_LIST: ${{ secrets.EVERGINE_EMAILREPORT_LIST }}
      EMAIL_FROM: ${{ secrets.EVERGINE_EMAIL }}