# Binding CI - Simple Template
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    uses: EvergineTeam/evergine-standards/.github/workflows/binding-common-ci.yml@main
    with:
      generator-project: "YourBindingGen/YourBindingGen/YourBindingGen.csproj"  # Path to your generator .csproj
      generator-name: "YourBindingGen"             # Name of your generator executable
      binding-project: "Bindings/Evergine.Bindings.YourBinding/Evergine.Bindings.YourBinding.csproj" # Path to your binding .csproj
      target-framework: "net8.0"                   # Target framework for generator/binding
      runtime-identifier: "win-x64"                # Runtime identifier (win-x64, linux-x64, etc.)
      build-configuration: "Release"               # Build configuration (Release, Debug, etc.)
      nuget-artifacts: false                       # Upload NuGets as workflow artifacts
      revision: ${{ github.run_number }}           # Revision for date-based version (bindings style). Use with bindings.