# Binding CI - Simple Template

# This is a template for Pure .NET Binding repositories.
# Copy this file to your repository as `.github/workflows/CI.yml` and customize the inputs below.

# Prerequisites:
# 1. Your repository must have the 'binding' group synced from evergine-standards
# 2. The following scripts must be present:
#    - scripts/binding/Generate-Bindings-DotNet.ps1
#    - scripts/common/Generate-NuGets-DotNet.ps1
#    - scripts/common/Helpers.ps1
# 3. Your repository structure should follow the standard binding layout

# Customization:
# - Replace "YourBindingName" with your actual binding name
# - Update paths to match your project structure
# - Configure secrets in your repository settings

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    uses: EvergineTeam/evergine-standards/.github/workflows/binding-ci-simple.yml@main
    with:
      # Project Configuration
      project-name: "YourBindingName"              # Name shown in notifications
      main-branch: "main"                          # Your main branch name (main/master)
      
      # Versioning
      version-param: "revision"                    # "revision" for date-based (YYYY.M.D.revision) or "version" for direct version
      version-value: ""                            # Leave empty to use github.run_number, or specify a value
      
      # .NET Configuration
      dotnet-version: "8.x"                        # .NET SDK version
      nuget-version: "6.x"                         # NuGet CLI version
      
      # Generator Configuration
      generator-project: "YourBindingGen/YourBindingGen/YourBindingGen.csproj"  # Path to your generator .csproj
      generator-name: "YourBindingGen"             # Name of your generator executable
      target-framework: "net8.0"                   # Target framework for generator
      runtime-identifier: "win-x64"                # Runtime identifier (win-x64, linux-x64, etc.)
      
      # NuGet Packaging
      projects: "Bindings/Evergine.Bindings.YourBinding/Evergine.Bindings.YourBinding.csproj"  # Project(s) to pack
      output-folder: "nupkgs"                      # Output folder for NuGet packages
      
      # Build Configuration
      build-verbosity: "normal"                    # dotnet verbosity (quiet, minimal, normal, detailed, diagnostic)
      build-configuration: "Release"               # Build configuration (Release, Debug, etc.)
      
      # Debug Symbols
      include-symbols: false                       # Include symbol packages
      symbols-format: "snupkg"                     # Symbol format: snupkg (modern) or symbols.nupkg (legacy)
      
      # Notifications
      enable-email-notifications: true             # Send email on failure
    
    secrets:
      SENDGRID_TOKEN: ${{ secrets.WAVE_SENDGRID_TOKEN }}
      EMAIL_REPORT_LIST: ${{ secrets.EVERGINE_EMAILREPORT_LIST }}
      EMAIL_FROM: ${{ secrets.EVERGINE_EMAIL }}

# Tips:
# - For multiple projects, use multiline string:
#   projects: |
#     Project1/Project1.csproj
#     Project2/Project2.csproj
# 
# - For direct version (add-ons style):
#   version-param: "version"
#   version-value: "3.4.22.288-local"
#
# - For date-based version (bindings style):
#   version-param: "revision"
#   version-value: ""  # Uses github.run_number
