name: Sync Standards Reusable

on:
  workflow_call:
    inputs:
      org:
        description: "Organization of the standards repository"
        default: "EvergineTeam"
        required: false
        type: string
      repo:
        description: "Name of the standards repository" 
        default: "evergine-standards"
        required: false
        type: string
      ref:
        description: "Branch, tag, or commit to sync from"
        default: "main"
        required: false
        type: string
      target_branch:
        description: "Branch to apply changes to"
        default: "main"
        required: false
        type: string
      script_path:
        description: "Path where to download the sync script"
        default: "sync-standards.ps1"
        required: false
        type: string
      commit_message:
        description: "Commit message to use"
        required: false
        default: ""
        type: string
      mode:
        description: "auto (push then PR if needed) or pr (always PR)"
        default: "auto"
        required: false
        type: string
      dry_run:
        description: "Dry run mode - show what would be done without making changes"
        default: false
        required: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # allow push commits
      pull-requests: write # allow creating pull requests

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.target_branch }}
          fetch-depth: 0

      - name: Check for local script
        id: check_local
        run: |
          if [ -f "${{ inputs.script_path }}" ]; then
            echo "use_local=true" >> $GITHUB_OUTPUT
            echo "Using local script at ${{ inputs.script_path }}"
          else
            echo "use_local=false" >> $GITHUB_OUTPUT
            echo "Will download script to ${{ inputs.script_path }}"
          fi

      - name: Download sync script
        if: steps.check_local.outputs.use_local == 'false'
        run: |
          curl -o "${{ inputs.script_path }}" \
               "https://raw.githubusercontent.com/${{ inputs.org }}/${{ inputs.repo }}/${{ inputs.ref }}/scripts/sync-standards.ps1"

      - name: Run sync script
        shell: pwsh
        run: |
          ${{ inputs.script_path }} `
            -Org "${{ inputs.org }}" `
            -Repo "${{ inputs.repo }}" `
            -Ref "${{ inputs.ref }}" `
            ${{ inputs.dry_run && '-DryRun' || '' }}

      - name: Stage changes
        if: ${{ !inputs.dry_run }}
        shell: bash
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "CHANGES=false" >> $GITHUB_ENV
          else
            echo "CHANGES=true" >> $GITHUB_ENV
          fi

      - name: Show dry run summary
        if: ${{ inputs.dry_run }}
        shell: bash
        run: |
          echo "DRY RUN MODE - No changes will be committed or pushed"
          echo ""
          echo "Files that would be modified:"
          git status --porcelain || echo "No changes detected"
          echo ""
          echo "To apply these changes, run the workflow again without dry_run option."

      # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token 
      - name: Commit (if any)
        if: env.CHANGES == 'true' && !inputs.dry_run
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "${{ inputs.commit_message }}"

      # Direct push if there are changes and mode is auto
      - name: Try direct push
        if: env.CHANGES == 'true' && inputs.mode == 'auto' && github.event.repository.fork != true && !inputs.dry_run
        id: direct
        continue-on-error: true
        run: |
          git push
          echo "exit_code=$?" >> $GITHUB_OUTPUT

      # If push fails (e.g. protected branch) or if forced mode=pr → open PR
      - name: Create Pull Request
        if: >
          env.CHANGES == 'true' && !inputs.dry_run && (
            inputs.mode == 'pr' ||
            github.event.repository.fork == true ||
            steps.direct.outcome == 'failure' ||
            steps.direct.outputs.exit_code != '' && steps.direct.outputs.exit_code != '0'
          )
        uses: peter-evans/create-pull-request@v7
        with:
          branch: chore/sync-standards
          title: "Sync standards"
          body: "Automated update of shared standard files."
          commit-message: "${{ inputs.commit_message }}"
          labels: standards
          signoff: false
          delete-branch: true