name: Sync Standards Reusable

on:
  workflow_call:
    inputs:
      org:
        description: "Organization of the standards repository"
        default: "EvergineTeam"
        required: false
        type: string
      repo:
        description: "Name of the standards repository" 
        default: "evergine-standards"
        required: false
        type: string
      ref:
        description: "Branch, tag, or commit to sync from"
        default: "main"
        required: false
        type: string
      target_branch:
        description: "Branch to apply changes to"
        default: "main"
        required: false
        type: string
      script_path:
        description: "Path where to download the sync script"
        default: "sync-standards.ps1"
        required: false
        type: string
      commit_message:
        description: "Commit message to use"
        required: false
        default: ""
        type: string
      mode:
        description: "auto (push then PR if needed) or pr (always PR)"
        default: "auto"
        required: false
        type: string
      dry_run:
        description: "Dry run mode - show what would be done without making changes"
        default: false
        required: false
        type: boolean

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # allow push commits
      pull-requests: write # allow creating pull requests

    steps:
      - name: Checkout target branch
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.target_branch }}

      - name: Check for local script
        id: check_local
        run: |
          if [ -f "${{ inputs.script_path }}" ]; then
            echo "use_local=true" >> $GITHUB_OUTPUT
            echo "Using local script at ${{ inputs.script_path }}"
          else
            echo "use_local=false" >> $GITHUB_OUTPUT
            echo "Will download script to ${{ inputs.script_path }}"
          fi

      - name: Download sync script
        if: steps.check_local.outputs.use_local == 'false'
        run: |
          curl -o "${{ github.workspace }}/${{ inputs.script_path }}" \
               "https://raw.githubusercontent.com/${{ inputs.org }}/${{ inputs.repo }}/${{ inputs.ref }}/scripts/sync-standards.ps1"

      - name: Run sync script
        shell: pwsh
        run: |
          ${{ inputs.script_path }} `
            -Org "${{ inputs.org }}" `
            -Repo "${{ inputs.repo }}" `
            -Ref "${{ inputs.ref }}" `
            ${{ inputs.dry_run && '-DryRun' || '' }}

      - name: Commit, push or PR update
        uses: ./.github/actions/commit-and-push-or-pr-update
        with:
          commit_message: ${{ inputs.commit_message }}
          mode: ${{ inputs.mode }}
          labels: standards
          pr_branch_name: chore/sync-standards
          pr_title: Sync standards
          pr_body: Automated update of shared standard files.