name: Binding CI (Reusable)

description: >
  Reusable workflow for bindings.

on:
  workflow_call:
    inputs:
      generator-project:
        description: 'Path to the generator .csproj file'
        required: true
        type: string
      generator-name:
        description: 'Name of the generator/binding'
        required: true
        type: string
      binding-project:
        description: 'Path to the binding .csproj file'
        required: true
        type: string
      target-framework:
        description: 'Target framework for the binding'
        required: false
        type: string
        default: 'net8.0'
      runtime-identifier:
        description: 'Runtime identifier (optional, for platform-specific bindings)'
        required: false
        type: string
        default: 'win-x64'
      build-verbosity:
        description: 'dotnet verbosity level'
        required: false
        type: string
        default: 'normal'
      build-configuration:
        description: 'Build configuration (Release, Debug, etc.)'
        required: false
        type: string
        default: 'Release'
      main-branch:
        description: 'Main branch name (master/main)'
        required: false
        type: string
        default: 'main'
      nuget-artifacts:
        description: 'Upload generated NuGets as workflow artifacts (true/false)'
        required: false
        type: boolean
        default: false
      bindings-script-path:
        description: 'Path to the Generate-Bindings-DotNet.ps1 script'
        required: false
        type: string
        default: './Generate-Bindings-DotNet.ps1'
      nugets-script-path:
        description: 'Path to the Generate-NuGets-DotNet.ps1 script'
        required: false
        type: string
        default: './Generate-NuGets-DotNet.ps1'
      helpers-path:
        description: 'Path to the Helpers.ps1 file. Defaults to Helpers.ps1 in the same directory as the script.'
        required: false
        default: './Helpers.ps1'
jobs:
  update_and_generate:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate bindings
        uses: EvergineTeam/evergine-standards/.github/actions/binding-generate-bindings-dotnet@main
        with:
          script-path: ${{ inputs.bindings-script-path }}
          generator-project: ${{ inputs.generator-project }}
          generator-name: ${{ inputs.generator-name }}
          target-framework: ${{ inputs.target-framework }}
          runtime-identifier: ${{ inputs.runtime-identifier }}
          build-verbosity: ${{ inputs.build-verbosity }}
          build-configuration: ${{ inputs.build-configuration }}

      - name: Build binding project
        shell: pwsh
        run: |
          dotnet build "${{ inputs.binding-project }}" -c "${{ inputs.build-configuration }}" -v "${{ inputs.build-verbosity }}" --framework "${{ inputs.target-framework }}"

      - name: Generate NuGets (optional)
        if: inputs.nuget-artifacts == true
        uses: EvergineTeam/evergine-standards/.github/actions/binding-generate-nugets-dotnet@main
        with:
          script-path: ${{ inputs.nugets-script-path }}
          helpers-path: ${{ inputs.helpers-path }}
          binding-project: ${{ inputs.binding-project }}
          target-framework: ${{ inputs.target-framework }}
          runtime-identifier: ${{ inputs.runtime-identifier }}
          build-verbosity: ${{ inputs.build-verbosity }}
          build-configuration: ${{ inputs.build-configuration }}

      - name: Upload NuGets as artifact
        if: inputs.nuget-artifacts == true
        uses: actions/upload-artifact@v4
        with:
          name: nugets
          path: '**/*.nupkg'
