name: Binding Simple CD (Reusable)

description: >
  Reusable workflow for publishing NuGets for pure .NET bindings (no XML update).

on:
  workflow_call:
    inputs:
      generator-project:
        description: 'Path to the generator .csproj file'
        required: true
        type: string
      generator-name:
        description: 'Name of the generator/binding'
        required: true
        type: string
      binding-project:
        description: 'Path to the binding .csproj file'
        required: true
        type: string
      target-framework:
        description: 'Target framework for the binding'
        required: false
        type: string
        default: 'net8.0'
      runtime-identifier:
        description: 'Runtime identifier (optional, for platform-specific bindings)'
        required: false
        type: string
        default: 'win-x64'
      build-verbosity:
        description: 'dotnet verbosity level'
        required: false
        type: string
        default: 'normal'
      build-configuration:
        description: 'Build configuration (Release, Debug, etc.)'
        required: false
        type: string
        default: 'Release'
      version:
        description: 'Direct version string to use for packages (e.g., "3.4.22.288-local")'
        required: false
        type: string
        default: ''
      output-folder:
        description: 'Base folder for NuGet package output'
        required: false
        type: string
        default: 'nupkgs'
      include-symbols:
        description: 'Whether to include debug symbols in packages'
        required: false
        type: boolean
        default: false
      symbols-format:
        description: 'Symbol package format: snupkg (modern) or symbols.nupkg (legacy)'
        required: false
        type: string
        default: 'snupkg'
      bindings-script-path:
        description: 'Path to the Generate-Bindings-DotNet.ps1 script'
        required: false
        type: string
        default: 'build/scripts/Generate-Bindings-DotNet.ps1'
      nugets-script-path:
        description: 'Path to the Generate-NuGets-DotNet.ps1 script'
        required: false
        type: string
        default: 'build/scripts/Generate-NuGets-DotNet.ps1'
      helpers-path:
        description: 'Path to the Helpers.ps1 file. Defaults to Helpers.ps1 in the same directory as the script.'
        required: false
        type: string
        default: 'build/scripts/Helpers.ps1'
      publish-enabled:
        description: 'Publish to Nuget.org'
        required: false
        type: boolean
        default: true
      dotnet-version:
        description: 'Version of .NET SDK to use (e.g., 8.x)'
        required: false
        type: string
        default: '8.x'
      nuget-version:
        description: 'Version of NuGet CLI to use (e.g., 6.x)'
        required: false
        type: string
        default: '6.x'
      enable-email-notifications:
        description: 'Enable email notifications on failure'
        required: false
        type: boolean
        default: false

jobs:
  build_and_publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Setup NuGet CLI
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: ${{ inputs.nuget-version }}

      - name: Generate bindings
        uses: EvergineTeam/evergine-standards/.github/actions/binding-generate-bindings-dotnet@feature/sync-bindings
        with:
          script-path: ${{ inputs.bindings-script-path }}
          generator-project: ${{ inputs.generator-project }}
          generator-name: ${{ inputs.generator-name }}
          target-framework: ${{ inputs.target-framework }}
          runtime-identifier: ${{ inputs.runtime-identifier }}
          build-verbosity: ${{ inputs.build-verbosity }}
          build-configuration: ${{ inputs.build-configuration }}

      - name: Generate NuGets
        uses: EvergineTeam/evergine-standards/.github/actions/binding-generate-nugets-dotnet@feature/sync-bindings
        with:
          script-path: ${{ inputs.nugets-script-path }}
          helpers-path: ${{ inputs.helpers-path }}
          projects: ${{ inputs.binding-project }}
          output-folder: ${{ inputs.output-folder }}
          build-verbosity: ${{ inputs.build-verbosity }}
          build-configuration: ${{ inputs.build-configuration }}
          version: ${{ inputs.version }}
          include-symbols: ${{ inputs.include-symbols }}
          symbols-format: ${{ inputs.symbols-format }}

      - name: Publish NuGet
        if: ${{ success() && inputs.publish-enabled == true }}
        env:
          token: ${{ secrets.EVERGINE_NUGETORG_TOKEN }}
        run: |
          cd ${{ inputs.output-folder }}
          ls *.nupkg
          dotnet nuget push "**/*.nupkg" --skip-duplicate --no-symbols -k "$env:token" -s https://api.nuget.org/v3/index.json

      - name: SendGrid Mail Action
        if: ${{ failure() && inputs.enable-email-notifications == true }}
        uses: mmichailidis/sendgrid-mail-action@v1.1
        with:
          sendgrid-token: ${{ secrets.WAVE_SENDGRID_TOKEN }}
          mail: ${{ secrets.EVERGINE_EMAILREPORT_LIST }}
          from: ${{ secrets.EVERGINE_EMAIL }}
          subject: Binding ${{ inputs.generator-name }} - CD NuGet publish failed
          individual: false
          text: Something went wrong when publishing NuGets for binding ${{ inputs.generator-name }}.
