name: Binding CI - Simple (Reusable)

on:
  workflow_call:
    inputs:
      project-name:
        description: 'Name of the project for notifications'
        required: true
        type: string
      main-branch:
        description: 'Main branch name (master/main)'
        required: false
        type: string
        default: 'main'
      version-param:
        description: 'Parameter name for version: "revision" (date-based) or "version" (direct)'
        required: false
        type: string
        default: 'revision'
      version-value:
        description: 'Version value (revision number or full version string, depending on version-param)'
        required: false
        type: string
        default: ''
      dotnet-version:
        description: 'DotNet version to use'
        required: false
        type: string
        default: '8.x'
      nuget-version:
        description: 'NuGet version to use'
        required: false
        type: string
        default: '6.x'
      generator-project:
        description: 'Path to the generator .csproj file'
        required: true
        type: string
      generator-name:
        description: 'Name of the generator/binding'
        required: true
        type: string
      target-framework:
        description: 'Target framework for the binding'
        required: false
        type: string
        default: 'net8.0'
      runtime-identifier:
        description: 'Runtime identifier (optional, for platform-specific bindings)'
        required: false
        type: string
        default: 'win-x64'
      projects:
        description: 'Project(s) to pack (.csproj paths, comma or newline separated)'
        required: true
        type: string
      output-folder:
        description: 'Base folder for NuGet package output'
        required: false
        type: string
        default: 'nupkgs'
      build-verbosity:
        description: 'dotnet verbosity level'
        required: false
        type: string
        default: 'normal'
      build-configuration:
        description: 'Build configuration (Release, Debug, etc.)'
        required: false
        type: string
        default: 'Release'
      include-symbols:
        description: 'Whether to include debug symbols in packages'
        required: false
        type: boolean
        default: false
      symbols-format:
        description: 'Symbol package format (snupkg or symbols.nupkg)'
        required: false
        type: string
        default: 'snupkg'
      enable-email-notifications:
        description: 'Enable email notifications on failure'
        required: false
        type: boolean
        default: true
    secrets:
      SENDGRID_TOKEN:
        required: false
      EMAIL_REPORT_LIST:
        required: false
      EMAIL_FROM:
        required: false

env:
  nugetOutputPath: ${{ inputs.output-folder }}

jobs:
  build_and_publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
        with:
          nuget-version: ${{ inputs.nuget-version }}
      
      - name: Generate Bindings
        uses: EvergineTeam/evergine-standards/.github/actions/binding-generate-bindings-dotnet@main
        with:
          generator-project: ${{ inputs.generator-project }}
          generator-name: ${{ inputs.generator-name }}
          target-framework: ${{ inputs.target-framework }}
          runtime-identifier: ${{ inputs.runtime-identifier }}
          build-verbosity: ${{ inputs.build-verbosity }}
          build-configuration: ${{ inputs.build-configuration }}
      
      - name: Generate NuGet Packages
        id: generate-nugets
        uses: EvergineTeam/evergine-standards/.github/actions/binding-generate-nugets-dotnet@main
        with:
          version: ${{ inputs.version-param == 'version' && inputs.version-value || '' }}
          revision: ${{ inputs.version-param == 'revision' && inputs.version-value || github.run_number }}
          projects: ${{ inputs.projects }}
          output-folder: ${{ inputs.output-folder }}
          build-verbosity: ${{ inputs.build-verbosity }}
          build-configuration: ${{ inputs.build-configuration }}
          include-symbols: ${{ inputs.include-symbols }}
          symbols-format: ${{ inputs.symbols-format }}
      
      - name: Upload NuGet Packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ${{ steps.generate-nugets.outputs.output-path }}/*.nupkg
          if-no-files-found: error
      
      - name: Send Failure Notification
        if: ${{ failure() && inputs.enable-email-notifications }}
        uses: mmichailidis/sendgrid-mail-action@v1.1
        with:
          sendgrid-token: ${{ secrets.SENDGRID_TOKEN }}
          mail: ${{ secrets.EMAIL_REPORT_LIST }}
          from: ${{ secrets.EMAIL_FROM }}
          subject: ${{ inputs.project-name }} CI build has failed
          individual: false
          text: Something went wrong when building ${{ inputs.project-name }}
